
import React from 'react'
import HouseImg1 from '../assets/Image/HouseImg1.jpg';
import HouseImg2 from '../assets/Image/HouseImg2.jpg';
import HouseImg3 from '../assets/Image/HouseImg3.jpg';
import HouseImg4 from '../assets/Image/HouseImg4.jpg';
import { motion } from 'framer-motion';

function Work() {

    const cardSection = [
        {
            heading: "Solar Light to Electricity",
            para: "Solar panels are made up of photovoltaic (PV) cells that capture sunlight. When sunlight hits these cells, it excites electrons and generates direct current (DC) electricity. This process converts natural solar energy into usable electrical power at the panel level."
        },
        {
            heading: "Converting Direct Current (DC) to Alternating Current (AC)",
            para: "The electricity produced by solar panels is direct current (DC), which is not suitable for most household and commercial appliances. The generated DC power is sent to a solar inverter, where it is converted into alternating current (AC), making it safe and usable for everyday applications."
        },
        {
            heading: "Consuming or Exporting Electricity to the Grid",
            para: "Once converted into AC power, the electricity can be used immediately to power your home or business. If the system produces more energy than required, the excess electricity is exported to the utility grid through net metering, helping reduce future electricity bills."
        }
    ];

    const cards = [
        {
            img: HouseImg1,
            heading: "1. Solar Panels Capture Sunlight",
            para: "Solar PV panels installed by AP POWER ENERGY SOLUTIONS absorb sunlight using high-efficiency silicon cells. When sunlight hits the panels, electrons are activated, generating direct current (DC) electricity."
        },

        {
            img: HouseImg2,
            heading: "2. Inverter Converts DC to AC Power",
            para: "The DC electricity generated by the panels is sent to a solar inverter. The inverter converts DC into alternating current (AC), which is the standard form of electricity used to power homes, offices, and industrial equipment."
        },

        {
            img: HouseImg3,
            heading: "3. Excess Electricity Is Stored or Exported",
            para: "When the solar system produces more electricity than required, the excess power can be stored in a battery system or exported to the utility grid through net metering, helping reduce overall electricity costs."
        },

        {
            img: HouseImg4,
            heading: "4. Grid Power Supports Additional Energy Needs",
            para: "If solar generation is insufficient—such as during night-time or peak usage—additional electricity is automatically drawn from the grid, ensuring uninterrupted power supply at all times."
        },

    ];

    return (
        <section className="w-full bg-white md:my-5 px-4 lg:px-6">
            <h1 className='text-3xl md:text-5xl text-[#1F2933] font-semibold text-center mt-2 md:mt-8 mb-10 md:mb-20'>
                How It Works?
            </h1>

            {/* card-section */}
            <div className="max-w-280 mx-auto flex flex-col md:flex-row gap-7">

                {cardSection.map((item, index) => (
                    <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8, delay: index * 0.3, ease: "easeInOut" }}
                        viewport={{ once: true }}
                        className="w-full md:w-1/3 p-8 bg-blue-50 rounded-[50px] shadow-[0_0_12px_rgba(0,0,0,0.15)] shadow-neutral-500 hover:scale-102 transition-all duration-300">

                        <h1 className='text-3xl lg:text-4xl text-[#1F2933] font-medium pb-6 lg:pb-10 leading-10'>
                            {item.heading}
                        </h1>

                        <p className='text-lg md:text-xl'>
                            {item.para}
                        </p>
                    </motion.div>
                ))}
            </div>

            {/* cards */}
            <div className="max-w-280 mx-auto flex flex-col md:grid grid-cols-2 lg:flex lg:flex-row my-18 md:my-25">
                {cards.map((item, index) => (
                    <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{
                            duration: 0.8,
                            delay: index * 0.2, // Index ke hisab se automatic delay (0, 0.2, 0.4...)
                            ease: "easeOut"
                        }}
                        className='w-full'
                    >
                        <motion.img
                            src={item.img}
                            alt='HouseImage'
                            whileHover={{ scale: 1.05 }}
                            transition={{ duration: 0.4 }}
                            className='w-full object-cover'
                        />

                        <h1 className='w-full lg:w-60 py-1 px-2 text-xl text-start text-[#1F2933] font-semibold'>
                            {item.heading}
                        </h1>

                        <p className='w-full lg:w-60 py-4 px-2 text-xl text-start text-[#1F2933]'>
                            {item.para}
                        </p>
                    </motion.div>
                ))}
            </div>
        </section>
    )
}

export default Work;